name: Docs
on:
  push:
    branches:
      - master
      - test-docs
  workflow_dispatch: null

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - run: pip install --upgrade pip && pip install mkdocs==1.4.2 mkdocs-gen-files==0.4.0 mkdocs-literate-nav==0.6.0 mkdocs-material==9.0.15 mkdocstrings==0.20.0 mkdocstrings-python==0.8.3 mkdocs-section-index==0.3.5
      - name: Publish docs
        run: mkdocs gh-deploy --verbose  --force